# Generated by Django 3.1.6 on 2021-05-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kenlist', '0002_auto_20210503_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='violation',
            new_name='ni',
        ),
    ]
