# Generated by Django 3.1.6 on 2021-05-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kenlist', '0003_auto_20210503_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='empid',
            new_name='eadd',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='namestudent',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='sid',
            new_name='vision',
        ),
    ]
